spring.data.mongodb.uri=mongodb+srv://nishthaDB:Percy09@cluster0.xib4hn5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=expenseSplitdb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true